development: &non_production_settings
  site_url: http://localhost:3000
  site_name: WRS HQ Bills
  admin_email: admin@wrs.oib.com
  
test:
  <<: *non_production_settings

staging:
  site_url: http://staging.example.com
  site_name: WRS HQ Bills
  admin_email: admin@wrs.oib.com
  
production:
  site_url: http://www.example.com
  site_name: WRS HQ Bills
  admin_email: admin@wrs.oib.com
