development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Pay The House
  admin_email: thehouse@paythehouse.com
  
test:
  <<: *non_production_settings

staging:
  site_url: http://staging.example.com
  site_name: Pay The House
  admin_email: thehouse@paythehouse.com
  
production:
  site_url: http://www.paythehouse.com
  site_name: Pay The House
  admin_email: thehouse@paythehouse.com
